### ISSUE TITLE
No sdist available to download to be able to build a conda forge recipe

### ISSUE THREAD

**Issue by goanpeca** [hnguyentt/mousechd-napari#2]
Hello team, while trying to create a conda recipe on conda forge for this plugin, we noticed that there are no sdist available on the pypi page

https://pypi.org/project/napari-nyxus/#files

The source code (sdist) is required to be able to create a conda package.

Could you upload this?

Thanks 🚀 !

**Comment by hnguyentt** [comment]
Hello, we don't face any issue that you mentioned. Could you give some code for reproduction and issue log?

Pleasse follow this instruction for installation:
```
conda create -n mousechd_napari python=3.9
conda activate mousechd_napari
pip install "napari[all]"
pip install mousechd-napari
napari
```
